# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 862c38bd36f0f5534814cea76c0dd1b5626fd5db6f94043b4f9c6cb78638a034dd546f53664518e25feea03cc8f4f56b7f3a8d4c25e80efa68a4ba1f0091347a

test:
  secret_key_base: 81aa62a971f1d798332fb49f66e125848ba4e3657d0cd8897c243e3d53546b6ddf5d3d1bd781e824f6553c4b00f499df4a9773462cec73e00e05fc4c3a0a8199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
